In [1]:
import torch

print(torch.__version__)

2.7.1+cu118

In [2]:
import os

project_dir = os.path.expanduser("~/work/transformer_chatbot")
data_dir = os.path.join(project_dir, "data")

os.makedirs(data_dir, exist_ok=True)

print("project_dir:", project_dir)
print("data_dir:", data_dir)
print("프로젝트 폴더 존재 여부:", os.path.exists(project_dir))
print("데이터 폴더 존재 여부:", os.path.exists(data_dir))

project_dir: /home/jovyan/work/transformer_chatbot
data_dir: /home/jovyan/work/transformer_chatbot/data
프로젝트 폴더 존재 여부: True
데이터 폴더 존재 여부: True

In [3]:
import urllib.request

url = "https://github.com/songys/Chatbot_data/raw/master/ChatbotData.csv"
data_path = os.path.join(data_dir, "ChatbotData.csv")

if not os.path.exists(data_path):
    urllib.request.urlretrieve(url, data_path)
    print("다운로드 완료:", data_path)
else:
    print("이미 파일이 있습니다:", data_path)

print("파일 존재 여부:", os.path.exists(data_path))

다운로드 완료: /home/jovyan/work/transformer_chatbot/data/ChatbotData.csv
파일 존재 여부: True

In [4]:
import pandas as pd

df = pd.read_csv(data_path)

print("데이터 크기:", df.shape)
print("컬럼명:", df.columns.tolist())

df.head()

데이터 크기: (11823, 3)
컬럼명: ['Q', 'A', 'label']

                 Q            A  label
0           12시 땡!   하루가 또 가네요.      0
1      1지망 학교 떨어졌어    위로해 드립니다.      0
2     3박4일 놀러가고 싶다  여행은 언제나 좋죠.      0
3  3박4일 정도 놀러가고 싶다  여행은 언제나 좋죠.      0
4          PPL 심하네   눈살이 찌푸려지죠.      0

In [5]:
print("결측치 확인")
print(df.isnull().sum())

print("\nlabel 분포")
print(df["label"].value_counts().sort_index())

print("\n질문 길이 통계")
print(df["Q"].astype(str).str.len().describe())

print("\n답변 길이 통계")
print(df["A"].astype(str).str.len().describe())

결측치 확인
Q        0
A        0
label    0
dtype: int64

label 분포
label
0    5290
1    3570
2    2963
Name: count, dtype: int64

질문 길이 통계
count    11823.000000
mean        12.879049
std          6.167467
min          1.000000
25%          9.000000
50%         12.000000
75%         16.000000
max         56.000000
Name: Q, dtype: float64

답변 길이 통계
count    11823.000000
mean        15.015140
std          6.701835
min          1.000000
25%         10.000000
50%         14.000000
75%         18.000000
max         76.000000
Name: A, dtype: float64

In [6]:
import re

def preprocess_sentence(sentence):
    sentence = str(sentence).strip()

    # 구두점 앞뒤에 공백 추가
    sentence = re.sub(r"([?.!,])", r" \1 ", sentence)

    # 한글, 자음/모음, 영어, 숫자, 기본 구두점만 남기기
    sentence = re.sub(r"[^가-힣ㄱ-ㅎㅏ-ㅣa-zA-Z0-9?.!,]+", " ", sentence)

    # 여러 공백을 하나로 정리
    sentence = re.sub(r"\s+", " ", sentence)

    return sentence.strip()

In [8]:
import re

def preprocess_sentence(sentence):
    sentence = str(sentence).strip()

    # 구두점 앞뒤에 공백 추가
    sentence = re.sub(r"([?.!,])", r" \1 ", sentence)

    # 한글, 자음/모음, 영어, 숫자, 기본 구두점만 남기기
    sentence = re.sub(r"[^가-힣ㄱ-ㅎㅏ-ㅣa-zA-Z0-9?.!,]+", " ", sentence)

    # 여러 공백을 하나로 정리
    sentence = re.sub(r"\s+", " ", sentence)

    return sentence.strip()

In [9]:
test_sentences = [
    "오늘 너무 힘들어ㅠㅠ",
    "SNS 시간낭비인 거 아는데 매일 하는 중",
    "PPL 심하네!!!",
    "3박4일 놀러가고 싶다",
    "나 잘할 수 있을까?"
]

for s in test_sentences:
    print("원문:", s)
    print("전처리:", preprocess_sentence(s))
    print("-" * 50)

원문: 오늘 너무 힘들어ㅠㅠ
전처리: 오늘 너무 힘들어ㅠㅠ
--------------------------------------------------
원문: SNS 시간낭비인 거 아는데 매일 하는 중
전처리: SNS 시간낭비인 거 아는데 매일 하는 중
--------------------------------------------------
원문: PPL 심하네!!!
전처리: PPL 심하네 ! ! !
--------------------------------------------------
원문: 3박4일 놀러가고 싶다
전처리: 3박4일 놀러가고 싶다
--------------------------------------------------
원문: 나 잘할 수 있을까?
전처리: 나 잘할 수 있을까 ?
--------------------------------------------------

In [10]:
questions = df["Q"].apply(preprocess_sentence).tolist()
answers = df["A"].apply(preprocess_sentence).tolist()

print("전처리된 질문 개수:", len(questions))
print("전처리된 답변 개수:", len(answers))

print("\n예시 5개")
for i in range(5):
    print("Q:", questions[i])
    print("A:", answers[i])
    print("-" * 50)

전처리된 질문 개수: 11823
전처리된 답변 개수: 11823

예시 5개
Q: 12시 땡 !
A: 하루가 또 가네요 .
--------------------------------------------------
Q: 1지망 학교 떨어졌어
A: 위로해 드립니다 .
--------------------------------------------------
Q: 3박4일 놀러가고 싶다
A: 여행은 언제나 좋죠 .
--------------------------------------------------
Q: 3박4일 정도 놀러가고 싶다
A: 여행은 언제나 좋죠 .
--------------------------------------------------
Q: PPL 심하네
A: 눈살이 찌푸려지죠 .
--------------------------------------------------

In [11]:
empty_questions = [q for q in questions if len(q.strip()) == 0]
empty_answers = [a for a in answers if len(a.strip()) == 0]

print("빈 질문 개수:", len(empty_questions))
print("빈 답변 개수:", len(empty_answers))

빈 질문 개수: 0
빈 답변 개수: 0

In [12]:
corpus_path = os.path.join(data_dir, "korean_chatbot_corpus.txt")

with open(corpus_path, "w", encoding="utf-8") as f:
    for q, a in zip(questions, answers):
        f.write(q + "\n")
        f.write(a + "\n")

print("corpus 저장 완료:", corpus_path)
print("파일 존재 여부:", os.path.exists(corpus_path))

corpus 저장 완료: /home/jovyan/work/transformer_chatbot/data/korean_chatbot_corpus.txt
파일 존재 여부: True

In [13]:
with open(corpus_path, "r", encoding="utf-8") as f:
    for i in range(10):
        print(f.readline().strip())

12시 땡 !
하루가 또 가네요 .
1지망 학교 떨어졌어
위로해 드립니다 .
3박4일 놀러가고 싶다
여행은 언제나 좋죠 .
3박4일 정도 놀러가고 싶다
여행은 언제나 좋죠 .
PPL 심하네
눈살이 찌푸려지죠 .

In [15]:
!pip install sentencepiece

Collecting sentencepiece
  Downloading sentencepiece-0.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Downloading sentencepiece-0.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 9.2 MB/s eta 0:00:00a 0:00:01
Installing collected packages: sentencepiece
Successfully installed sentencepiece-0.2.1

In [16]:
import sentencepiece as spm

print("sentencepiece import 성공")

sentencepiece import 성공

In [17]:
import sentencepiece as spm

vocab_size = 8000
spm_prefix = os.path.join(project_dir, "spm_kor_chatbot")

spm.SentencePieceTrainer.Train(
    input=corpus_path,
    model_prefix=spm_prefix,
    vocab_size=vocab_size,
    model_type="bpe",
    character_coverage=0.9995,
    pad_id=0,
    bos_id=1,
    eos_id=2,
    unk_id=3
)

print("SentencePiece 모델 학습 완료")
print("model 파일:", spm_prefix + ".model")
print("vocab 파일:", spm_prefix + ".vocab")

SentencePiece 모델 학습 완료
model 파일: /home/jovyan/work/transformer_chatbot/spm_kor_chatbot.model
vocab 파일: /home/jovyan/work/transformer_chatbot/spm_kor_chatbot.vocab

sentencepiece_trainer.cc(78) LOG(INFO) Starts training with :
trainer_spec {
  input: /home/jovyan/work/transformer_chatbot/data/korean_chatbot_corpus.txt
  input_format:
  model_prefix: /home/jovyan/work/transformer_chatbot/spm_kor_chatbot
  model_type: BPE
  vocab_size: 8000
  self_test_sample_size: 0
  character_coverage: 0.9995
  input_sentence_size: 0
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 0
  pretokenization_delimiter:
  treat_whitespace_as_suffix: 0
  allow_whitespace_only_pieces: 0
  required_chars:
  byte_fallback: 0
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 0
  seed_sentencepieces_file:
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 3
  bos_id: 1
  eos_id: 2
  pad_id: 0
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  ⁇
  enable_differential_privacy: 0
  differential_privacy_noise_level: 0
  differential_privacy_clipping_threshold: 0
}
normalizer_spec {
  name: nmt_nfkc
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv:
}
denormalizer_spec {}
trainer_interface.cc(355) LOG(INFO) SentenceIterator is not specified. Using MultiFileSentenceIterator.
trainer_interface.cc(186) LOG(INFO) Loading corpus: /home/jovyan/work/transformer_chatbot/data/korean_chatbot_corpus.txt
trainer_interface.cc(411) LOG(INFO) Loaded all 23646 sentences
trainer_interface.cc(427) LOG(INFO) Adding meta_piece: <pad>
trainer_interface.cc(427) LOG(INFO) Adding meta_piece: <s>
trainer_interface.cc(427) LOG(INFO) Adding meta_piece: </s>
trainer_interface.cc(427) LOG(INFO) Adding meta_piece: <unk>
trainer_interface.cc(432) LOG(INFO) Normalizing sentences...
trainer_interface.cc(541) LOG(INFO) all chars count=369627
trainer_interface.cc(552) LOG(INFO) Done: 99.9505% characters are covered.
trainer_interface.cc(562) LOG(INFO) Alphabet size=1076
trainer_interface.cc(563) LOG(INFO) Final character coverage=0.999505
trainer_interface.cc(594) LOG(INFO) Done! preprocessed 23646 sentences.
trainer_interface.cc(600) LOG(INFO) Tokenizing input sentences with whitespace: 23646
trainer_interface.cc(611) LOG(INFO) Done! 20665
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=13942 min_freq=42
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1055 size=20 all=16155 active=1765 piece=▁거예요
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=776 size=40 all=16871 active=2481 piece=▁여
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=619 size=60 all=17534 active=3144 piece=▁좋아하는
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=427 size=80 all=18140 active=3750 piece=▁모
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=358 size=100 all=18869 active=4479 piece=▁전
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=357 min_freq=37
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=307 size=120 all=19303 active=1400 piece=▁뭐
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=262 size=140 all=19896 active=1993 piece=▁소
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=227 size=160 all=20320 active=2417 piece=▁비
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=206 size=180 all=20676 active=2773 piece=▁행
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=188 size=200 all=21048 active=3145 piece=▁관
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=188 min_freq=31
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=172 size=220 all=21402 active=1399 piece=▁재
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=155 size=240 all=21730 active=1727 piece=▁데
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=144 size=260 all=22051 active=2048 piece=▁자꾸
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=136 size=280 all=22433 active=2430 piece=▁고백
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=130 size=300 all=22786 active=2783 piece=▁먼저
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=130 min_freq=26
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=122 size=320 all=23119 active=1468 piece=▁헤어진지
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=115 size=340 all=23449 active=1798 piece=▁버
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=108 size=360 all=23665 active=2014 piece=▁돈
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=104 size=380 all=23991 active=2340 piece=▁하루
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=99 size=400 all=24387 active=2736 piece=▁함
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=99 min_freq=22
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=92 size=420 all=24670 active=1501 piece=▁남자친구
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=87 size=440 all=24891 active=1722 piece=다가
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=85 size=460 all=25147 active=1978 piece=▁사람은
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=81 size=480 all=25388 active=2219 piece=하네
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=77 size=500 all=25664 active=2495 piece=▁설
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=77 min_freq=20
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=75 size=520 all=25889 active=1496 piece=▁어떨까요
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=72 size=540 all=26117 active=1724 piece=▁해도
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=68 size=560 all=26392 active=1999 piece=▁그만
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=66 size=580 all=26558 active=2165 piece=▁휴
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=64 size=600 all=26744 active=2351 piece=▁항상
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=64 min_freq=18
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=62 size=620 all=26910 active=1504 piece=▁문제
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=60 size=640 all=27172 active=1766 piece=▁상황
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=57 size=660 all=27419 active=2013 piece=▁개
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=56 size=680 all=27625 active=2219 piece=▁가보세요
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=54 size=700 all=27747 active=2341 piece=▁충분히
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=53 min_freq=16
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=52 size=720 all=27899 active=1540 piece=▁열심히
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=50 size=740 all=28039 active=1680 piece=▁종
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=49 size=760 all=28201 active=1842 piece=▁만남
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=48 size=780 all=28329 active=1970 piece=으니까요
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=47 size=800 all=28474 active=2115 piece=▁부��님
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=47 min_freq=15
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=46 size=820 all=28579 active=1520 piece=▁헤어지고
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=44 size=840 all=28711 active=1652 piece=더니
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=43 size=860 all=28852 active=1793 piece=▁살아
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=42 size=880 all=28946 active=1887 piece=▁잊혀
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=41 size=900 all=29065 active=2006 piece=▁재밌
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=41 min_freq=13
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=40 size=920 all=29208 active=1582 piece=▁소개팅
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=38 size=940 all=29323 active=1697 piece=▁끊
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=38 size=960 all=29515 active=1889 piece=▁잘하는
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=37 size=980 all=29667 active=2041 piece=▁정도
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=36 size=1000 all=29813 active=2187 piece=▁붙잡
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=36 min_freq=13
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=35 size=1020 all=29937 active=1604 piece=같아
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=34 size=1040 all=30077 active=1744 piece=▁익
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=34 size=1060 all=30212 active=1879 piece=드릴게요
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=33 size=1080 all=30361 active=2028 piece=▁힘내세요
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=32 size=1100 all=30466 active=2133 piece=▁아닌데
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=32 min_freq=12
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=31 size=1120 all=30559 active=1617 piece=▁무엇
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=30 size=1140 all=30651 active=1709 piece=▁관리
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=29 size=1160 all=30750 active=1808 piece=어야
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=29 size=1180 all=30864 active=1922 piece=이었을
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=28 size=1200 all=30986 active=2044 piece=▁꿈에
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=28 min_freq=11
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=28 size=1220 all=31039 active=1602 piece=여보세요
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=27 size=1240 all=31139 active=1702 piece=▁싸우
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=26 size=1260 all=31160 active=1723 piece=▁ᅲ
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=26 size=1280 all=31259 active=1822 piece=▁소식
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=26 size=1300 all=31338 active=1901 piece=▁때까지
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=26 min_freq=10
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=25 size=1320 all=31418 active=1647 piece=아서
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=25 size=1340 all=31546 active=1775 piece=▁알고
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=25 size=1360 all=31605 active=1834 piece=▁힘들죠
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=24 size=1380 all=31697 active=1926 piece=▁미치
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=24 size=1400 all=31771 active=2000 piece=▁알려줘
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=24 min_freq=10
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=23 size=1420 all=31820 active=1636 piece=▁먹을
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=23 size=1440 all=31939 active=1755 piece=▁드디어
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=22 size=1460 all=31999 active=1815 piece=▁경우
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=22 size=1480 all=32050 active=1866 piece=▁차분
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=22 size=1500 all=32114 active=1930 piece=▁거기까지
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=22 min_freq=9
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=21 size=1520 all=32254 active=1741 piece=▁10
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=21 size=1540 all=32320 active=1807 piece=답니다
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=21 size=1560 all=32359 active=1846 piece=▁자연스러운
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=20 size=1580 all=32463 active=1950 piece=야할
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=20 size=1600 all=32573 active=2060 piece=▁집중
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=20 min_freq=9
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=20 size=1620 all=32609 active=1658 piece=▁준비가
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=19 size=1640 all=32641 active=1690 piece=치가
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=19 size=1660 all=32748 active=1797 piece=▁오빠
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=19 size=1680 all=32834 active=1883 piece=▁받았어
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=18 size=1700 all=32843 active=1892 piece=▁걷
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=18 min_freq=9
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=18 size=1720 all=32971 active=1762 piece=이요
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=18 size=1740 all=33058 active=1849 piece=▁애랑
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=18 size=1760 all=33114 active=1905 piece=▁아름다
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=17 size=1780 all=33131 active=1922 piece=고생
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=17 size=1800 all=33267 active=2058 piece=▁나타
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=17 min_freq=8
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=17 size=1820 all=33323 active=1716 piece=▁있고
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=17 size=1840 all=33375 active=1768 piece=▁한동안
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=16 size=1860 all=33416 active=1809 piece=냐고
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=16 size=1880 all=33522 active=1915 piece=▁다니
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=16 size=1900 all=33575 active=1968 piece=▁없애
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=16 min_freq=8
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=16 size=1920 all=33653 active=1751 piece=▁SNS
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=16 size=1940 all=33670 active=1768 piece=▁사랑하는데
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=15 size=1960 all=33724 active=1822 piece=소한
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=15 size=1980 all=33816 active=1914 piece=▁돈을
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=15 size=2000 all=33887 active=1985 piece=▁일상
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=15 min_freq=8
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=15 size=2020 all=33932 active=1734 piece=▁소중한
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=15 size=2040 all=33939 active=1741 piece=▁않았어요
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=14 size=2060 all=33976 active=1778 piece=▁헛
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=14 size=2080 all=34115 active=1917 piece=▁나의
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=14 size=2100 all=34155 active=1957 piece=▁잡고
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=14 min_freq=7
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=14 size=2120 all=34181 active=1734 piece=▁벗어나
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=14 size=2140 all=34177 active=1730 piece=▁생각나네
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=14 size=2160 all=34165 active=1718 piece=▁이해해주세요
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=13 size=2180 all=34244 active=1797 piece=싶다
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=13 size=2200 all=34366 active=1919 piece=▁남았
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=13 min_freq=7
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=13 size=2220 all=34403 active=1748 piece=▁상태
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=13 size=2240 all=34478 active=1823 piece=▁전부
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=13 size=2260 all=34547 active=1892 piece=▁그동안
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=13 size=2280 all=34551 active=1896 piece=▁여사친
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=13 size=2300 all=34567 active=1912 piece=였나봐요
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=13 min_freq=7
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=13 size=2320 all=34567 active=1724 piece=▁않으니까요
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=12 size=2340 all=34626 active=1783 piece=되는
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=12 size=2360 all=34707 active=1864 piece=▁나왔
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=12 size=2380 all=34742 active=1899 piece=▁수가
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=12 size=2400 all=34774 active=1931 piece=▁취향
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=12 min_freq=7
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=12 size=2420 all=34813 active=1773 piece=▁됩니다
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=12 size=2440 all=34813 active=1773 piece=▁없어서
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=12 size=2460 all=34797 active=1757 piece=▁상대방이
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=12 size=2480 all=34782 active=1742 piece=▁응원합니다
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=11 size=2500 all=34813 active=1773 piece=▁합
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=11 min_freq=6
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=11 size=2520 all=34905 active=1830 piece=전에
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=11 size=2540 all=34955 active=1880 piece=▁나면
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=11 size=2560 all=34979 active=1904 piece=▁불행
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=11 size=2580 all=35026 active=1951 piece=▁움직
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=11 size=2600 all=35082 active=2007 piece=싶은데
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=11 min_freq=6
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=11 size=2620 all=35112 active=1777 piece=▁모습이
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=11 size=2640 all=35111 active=1776 piece=▁정리할
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=11 size=2660 all=35119 active=1784 piece=▁썸남이랑
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=11 size=2680 all=35107 active=1772 piece=▁고백해���세요
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=10 size=2700 all=35146 active=1811 piece=갔어
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=10 min_freq=6
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=10 size=2720 all=35230 active=1838 piece=인이
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=10 size=2740 all=35280 active=1888 piece=▁다되
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=10 size=2760 all=35315 active=1923 piece=▁변명
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=10 size=2780 all=35356 active=1964 piece=▁이뤄
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=10 size=2800 all=35402 active=2010 piece=이라고
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=10 min_freq=6
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=10 size=2820 all=35443 active=1805 piece=▁됐는데
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=10 size=2840 all=35440 active=1802 piece=▁아프다
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=10 size=2860 all=35430 active=1792 piece=▁태어난
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=10 size=2880 all=35439 active=1801 piece=▁생각하면
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=10 size=2900 all=35429 active=1791 piece=▁다르겠지만
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=10 min_freq=6
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=9 size=2920 all=35454 active=1797 piece=▁닮
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=9 size=2940 all=35522 active=1865 piece=라이
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=9 size=2960 all=35642 active=1985 piece=하대
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=9 size=2980 all=35678 active=2021 piece=▁대출
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=9 size=3000 all=35704 active=2047 piece=▁살기
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=9 min_freq=5
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=9 size=3020 all=35723 active=1804 piece=▁왔네
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=9 size=3040 all=35756 active=1837 piece=▁회식
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=9 size=3060 all=35833 active=1914 piece=▁가는데
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=9 size=3080 all=35832 active=1913 piece=▁되는지
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=9 size=3100 all=35821 active=1902 piece=▁알아차
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=9 min_freq=5
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=9 size=3120 all=35816 active=1784 piece=▁재미가
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=9 size=3140 all=35809 active=1777 piece=▁기다리면
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=9 size=3160 all=35805 active=1773 piece=▁있었으면
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=9 size=3180 all=35798 active=1766 piece=▁감사합니다
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=8 size=3200 all=35778 active=1746 piece=▁A

In [21]:
sp = spm.SentencePieceProcessor()
sp.Load(spm_prefix + ".model")

print("토크나이저 로드 완료")
print("vocab size:", sp.GetPieceSize())
print("pad id:", sp.pad_id())
print("bos id:", sp.bos_id())
print("eos id:", sp.eos_id())
print("unk id:", sp.unk_id())

토크나이저 로드 완료
vocab size: 8000
pad id: 0
bos id: 1
eos id: 2
unk id: 3

In [22]:
sample = "오늘 너무 힘들어ㅠㅠ"
sample = preprocess_sentence(sample)

pieces = sp.encode(sample, out_type=str)
ids = sp.encode(sample, out_type=int)
decoded = sp.decode(ids)

print("전처리 문장:", sample)
print("pieces:", pieces)
print("ids:", ids)
print("decoded:", decoded)

전처리 문장: 오늘 너무 힘들어ㅠㅠ
pieces: ['▁오늘', '▁너무', '▁힘들어', 'ᅲᅲ']
ids: [129, 56, 418, 2329]
decoded: 오늘 너무 힘들어ᅲᅲ

In [23]:
import torch
from torch.utils.data import Dataset, DataLoader

class ChatbotDataset(Dataset):
    def __init__(self, questions, answers, sp, max_length=40):
        self.questions = questions
        self.answers = answers
        self.sp = sp
        self.max_length = max_length

        self.pad_id = sp.pad_id()
        self.bos_id = sp.bos_id()
        self.eos_id = sp.eos_id()

    def encode_sentence(self, sentence):
        # BOS + 문장 token ids + EOS
        ids = [self.bos_id] + self.sp.encode(sentence, out_type=int) + [self.eos_id]

        # max_length보다 길면 자르기
        ids = ids[:self.max_length]

        # max_length보다 짧으면 PAD로 채우기
        padding = [self.pad_id] * (self.max_length - len(ids))
        ids = ids + padding

        return ids

    def __len__(self):
        return len(self.questions)

    def __getitem__(self, idx):
        question = self.questions[idx]
        answer = self.answers[idx]

        encoder_input = self.encode_sentence(question)
        answer_ids = self.encode_sentence(answer)

        # 디코더 입력과 정답을 한 칸 shift
        decoder_input = answer_ids[:-1]
        decoder_label = answer_ids[1:]

        return (
            torch.tensor(encoder_input, dtype=torch.long),
            torch.tensor(decoder_input, dtype=torch.long),
            torch.tensor(decoder_label, dtype=torch.long)
        )

In [24]:
MAX_LENGTH = 40
BATCH_SIZE = 32

dataset = ChatbotDataset(
    questions=questions,
    answers=answers,
    sp=sp,
    max_length=MAX_LENGTH
)

dataloader = DataLoader(
    dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)

print("Dataset 크기:", len(dataset))
print("DataLoader batch 개수:", len(dataloader))

Dataset 크기: 11823
DataLoader batch 개수: 370

In [25]:
encoder_input, decoder_input, decoder_label = dataset[0]

print("encoder_input 크기:", encoder_input.size())
print("decoder_input 크기:", decoder_input.size())
print("decoder_label 크기:", decoder_label.size())

print("\nencoder_input:", encoder_input)
print("\ndecoder_input:", decoder_input)
print("\ndecoder_label:", decoder_label)

print("\n질문 복원:")
print(sp.decode([int(x) for x in encoder_input if int(x) not in [sp.pad_id(), sp.bos_id(), sp.eos_id()]]))

print("\n디코더 입력 복원:")
print(sp.decode([int(x) for x in decoder_input if int(x) not in [sp.pad_id(), sp.bos_id(), sp.eos_id()]]))

print("\n디코더 정답 복원:")
print(sp.decode([int(x) for x in decoder_label if int(x) not in [sp.pad_id(), sp.bos_id(), sp.eos_id()]]))

encoder_input 크기: torch.Size([40])
decoder_input 크기: torch.Size([39])
decoder_label 크기: torch.Size([39])

encoder_input: tensor([   1, 5560, 6966, 3207,  108,    2,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0])

decoder_input: tensor([   1, 4492,  214, 5930,    4,    2,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0])

decoder_label: tensor([4492,  214, 5930,    4,    2,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0])

질문 복원:
12시 땡 !

디코더 입력 복원:
하루가 또 가네요 .

디코더 정답 복원:
하루가 또 가네요 .

In [26]:
for encoder_input, decoder_input, decoder_label in dataloader:
    print("encoder_input batch 크기:", encoder_input.size())
    print("decoder_input batch 크기:", decoder_input.size())
    print("decoder_label batch 크기:", decoder_label.size())
    break

encoder_input batch 크기: torch.Size([32, 40])
decoder_input batch 크기: torch.Size([32, 39])
decoder_label batch 크기: torch.Size([32, 39])

In [27]:
needed_names = [
    "PositionalEncoding",
    "scaled_dot_product_attention",
    "MultiHeadAttention",
    "EncoderLayer",
    "Encoder",
    "DecoderLayer",
    "Decoder",
    "Transformer",
    "create_padding_mask",
    "create_look_ahead_mask"
]

for name in needed_names:
    print(name, "정의 여부:", name in globals())

PositionalEncoding 정의 여부: False
scaled_dot_product_attention 정의 여부: False
MultiHeadAttention 정의 여부: False
EncoderLayer 정의 여부: False
Encoder 정의 여부: False
DecoderLayer 정의 여부: False
Decoder 정의 여부: False
Transformer 정의 여부: False
create_padding_mask 정의 여부: False
create_look_ahead_mask 정의 여부: False

In [28]:
NUM_LAYERS = 2
D_MODEL = 256
NUM_HEADS = 8
UNITS = 512
DROPOUT = 0.1
VOCAB_SIZE = sp.GetPieceSize()

print("VOCAB_SIZE:", VOCAB_SIZE)

VOCAB_SIZE: 8000

In [30]:
needed_names = [
    "PositionalEncoding",
    "scaled_dot_product_attention",
    "MultiHeadAttention",
    "EncoderLayer",
    "Encoder",
    "DecoderLayer",
    "Decoder",
    "Transformer",
    "create_padding_mask",
    "create_look_ahead_mask"
]

for name in needed_names:
    print(name, "정의 여부:", name in globals())

PositionalEncoding 정의 여부: False
scaled_dot_product_attention 정의 여부: False
MultiHeadAttention 정의 여부: False
EncoderLayer 정의 여부: False
Encoder 정의 여부: False
DecoderLayer 정의 여부: False
Decoder 정의 여부: False
Transformer 정의 여부: False
create_padding_mask 정의 여부: False
create_look_ahead_mask 정의 여부: False

In [31]:
import torch
import torch.nn as nn

class Transformer(nn.Module):
    def __init__(self,
                 vocab_size,
                 num_layers,
                 units,
                 d_model,
                 num_heads,
                 dropout=0.1):
        super(Transformer, self).__init__()

        self.encoder = Encoder(
            vocab_size=vocab_size,
            num_layers=num_layers,
            ff_dim=units,
            d_model=d_model,
            num_heads=num_heads,
            dropout=dropout
        )

        self.decoder = Decoder(
            vocab_size=vocab_size,
            num_layers=num_layers,
            ff_dim=units,
            d_model=d_model,
            num_heads=num_heads,
            dropout=dropout
        )

        self.final_linear = nn.Linear(d_model, vocab_size)

    def forward(self, inputs, dec_inputs):
        enc_padding_mask = create_padding_mask(inputs)
        look_ahead_mask = create_look_ahead_mask(dec_inputs)
        dec_padding_mask = create_padding_mask(inputs)

        enc_outputs = self.encoder(
            x=inputs,
            mask=enc_padding_mask
        )

        dec_outputs = self.decoder(
            x=dec_inputs,
            enc_outputs=enc_outputs,
            look_ahead_mask=look_ahead_mask,
            padding_mask=dec_padding_mask
        )

        logits = self.final_linear(dec_outputs)

        return logits

In [32]:
print("Transformer 정의 여부:", "Transformer" in globals())

Transformer 정의 여부: True

In [153]:
def decoder_inference(model, sentence, tokenizer, device='cpu', input_max_length=100, output_max_length=110):
    START_TOKEN = tokenizer.bos_id()
    END_TOKEN = tokenizer.eos_id()
    PAD_TOKEN = tokenizer.pad_id()

    sentence = preprocess_sentence(sentence)

    enc_input_ids = [START_TOKEN] + tokenizer.encode(sentence, out_type=int) + [END_TOKEN]
    enc_input_ids = enc_input_ids[:input_max_length]

    enc_input = torch.tensor([enc_input_ids], dtype=torch.long, device=device)
    dec_input = torch.tensor([[START_TOKEN]], dtype=torch.long, device=device)

    model.eval()

    with torch.no_grad():
        for _ in range(output_max_length):
            logits = model(enc_input, dec_input)
            last_step_logits = logits[:, -1, :]
            predicted_id = torch.argmax(last_step_logits, dim=-1)

            if predicted_id.item() == END_TOKEN:
                break

            predicted_id = predicted_id.unsqueeze(0)
            dec_input = torch.cat([dec_input, predicted_id], dim=1)

            if dec_input.size(1) >= output_max_length:
                break

    output_sequence = dec_input.squeeze(0).tolist()

    output_sequence = [
        token for token in output_sequence
        if token not in [START_TOKEN, END_TOKEN, PAD_TOKEN]
    ]

    return output_sequence


def sentence_generation(model, sentence, tokenizer, device='cpu'):
    output_seq = decoder_inference(
        model=model,
        sentence=sentence,
        tokenizer=tokenizer,
        device=device,
        input_max_length=100,
        output_max_length=110
    )

    predicted_sentence = tokenizer.decode(output_seq)

    print("입력:", sentence)
    print("출력:", predicted_sentence)
    print("-" * 80)

    return predicted_sentence

In [34]:
import math
import torch
import torch.nn as nn
import torch.nn.functional as F

In [35]:
class PositionalEncoding(nn.Module):
    def __init__(self, position, d_model):
        super(PositionalEncoding, self).__init__()

        self.pos_encoding = self.positional_encoding(position, d_model)

    def get_angles(self, position, i, d_model):
        angles = 1 / torch.pow(
            torch.tensor(10000.0),
            (2 * (i // 2)) / torch.tensor(float(d_model))
        )
        return position * angles

    def positional_encoding(self, position, d_model):
        angle_rads = self.get_angles(
            torch.arange(position).unsqueeze(1),
            torch.arange(d_model).unsqueeze(0),
            d_model
        )

        angle_rads[:, 0::2] = torch.sin(angle_rads[:, 0::2])
        angle_rads[:, 1::2] = torch.cos(angle_rads[:, 1::2])

        pos_encoding = angle_rads.unsqueeze(0)
        return pos_encoding.float()

    def forward(self, x):
        seq_len = x.size(1)
        return x + self.pos_encoding[:, :seq_len, :].to(x.device)

In [154]:
def scaled_dot_product_attention(query, key, value, mask=None):
    matmul_qk = torch.matmul(query, key.transpose(-1, -2))

    depth = key.size(-1)
    logits = matmul_qk / math.sqrt(depth)

    if mask is not None:
        logits += (mask * -1e9)

    attention_weights = F.softmax(logits, dim=-1)
    output = torch.matmul(attention_weights, value)

    return output, attention_weights

In [37]:
class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, num_heads):
        super(MultiHeadAttention, self).__init__()

        assert d_model % num_heads == 0

        self.num_heads = num_heads
        self.d_model = d_model
        self.depth = d_model // num_heads

        self.query_dense = nn.Linear(d_model, d_model)
        self.key_dense = nn.Linear(d_model, d_model)
        self.value_dense = nn.Linear(d_model, d_model)

        self.out_dense = nn.Linear(d_model, d_model)

    def split_heads(self, inputs):
        batch_size = inputs.size(0)

        inputs = inputs.view(batch_size, -1, self.num_heads, self.depth)
        return inputs.transpose(1, 2)

    def forward(self, query, key, value, mask=None):
        query = self.query_dense(query)
        key = self.key_dense(key)
        value = self.value_dense(value)

        query = self.split_heads(query)
        key = self.split_heads(key)
        value = self.split_heads(value)

        scaled_attention, attention_weights = scaled_dot_product_attention(
            query, key, value, mask
        )

        scaled_attention = scaled_attention.transpose(1, 2)

        batch_size = scaled_attention.size(0)
        concat_attention = scaled_attention.contiguous().view(
            batch_size, -1, self.d_model
        )

        outputs = self.out_dense(concat_attention)

        return outputs

In [38]:
def create_padding_mask(x):
    mask = (x == 0).float()
    mask = mask.unsqueeze(1).unsqueeze(2)
    return mask


def create_look_ahead_mask(x):
    seq_len = x.size(1)

    look_ahead_mask = 1 - torch.tril(torch.ones((seq_len, seq_len)))
    look_ahead_mask = look_ahead_mask.to(x.device)

    padding_mask = create_padding_mask(x)

    look_ahead_mask = look_ahead_mask.unsqueeze(0).unsqueeze(1)

    combined_mask = torch.max(look_ahead_mask, padding_mask)

    return combined_mask

In [39]:
class EncoderLayer(nn.Module):
    def __init__(self, d_model, num_heads, ff_dim, dropout=0.1):
        super(EncoderLayer, self).__init__()

        self.mha = MultiHeadAttention(d_model, num_heads)

        self.ffn = nn.Sequential(
            nn.Linear(d_model, ff_dim),
            nn.ReLU(),
            nn.Linear(ff_dim, d_model)
        )

        self.layernorm1 = nn.LayerNorm(d_model, eps=1e-6)
        self.layernorm2 = nn.LayerNorm(d_model, eps=1e-6)

        self.dropout1 = nn.Dropout(dropout)
        self.dropout2 = nn.Dropout(dropout)

    def forward(self, x, mask):
        attn_output = self.mha(x, x, x, mask)
        attn_output = self.dropout1(attn_output)

        out1 = self.layernorm1(x + attn_output)

        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output)

        out2 = self.layernorm2(out1 + ffn_output)

        return out2


class Encoder(nn.Module):
    def __init__(self, vocab_size, num_layers, ff_dim, d_model, num_heads, dropout=0.1):
        super(Encoder, self).__init__()

        self.d_model = d_model
        self.num_layers = num_layers

        self.embedding = nn.Embedding(vocab_size, d_model)
        self.pos_encoding = PositionalEncoding(1000, d_model)

        self.enc_layers = nn.ModuleList([
            EncoderLayer(d_model, num_heads, ff_dim, dropout)
            for _ in range(num_layers)
        ])

        self.dropout = nn.Dropout(dropout)

    def forward(self, x, mask):
        x = self.embedding(x)
        x *= math.sqrt(self.d_model)
        x = self.pos_encoding(x)
        x = self.dropout(x)

        for i in range(self.num_layers):
            x = self.enc_layers[i](x, mask)

        return x

In [40]:
class DecoderLayer(nn.Module):
    def __init__(self, d_model, num_heads, ff_dim, dropout=0.1):
        super(DecoderLayer, self).__init__()

        self.self_mha = MultiHeadAttention(d_model, num_heads)
        self.enc_dec_mha = MultiHeadAttention(d_model, num_heads)

        self.ffn = nn.Sequential(
            nn.Linear(d_model, ff_dim),
            nn.ReLU(),
            nn.Linear(ff_dim, d_model)
        )

        self.layernorm1 = nn.LayerNorm(d_model, eps=1e-6)
        self.layernorm2 = nn.LayerNorm(d_model, eps=1e-6)
        self.layernorm3 = nn.LayerNorm(d_model, eps=1e-6)

        self.dropout1 = nn.Dropout(dropout)
        self.dropout2 = nn.Dropout(dropout)
        self.dropout3 = nn.Dropout(dropout)

    def forward(self, x, enc_outputs, look_ahead_mask, padding_mask):
        attn1 = self.self_mha(x, x, x, look_ahead_mask)
        attn1 = self.dropout1(attn1)
        out1 = self.layernorm1(x + attn1)

        attn2 = self.enc_dec_mha(out1, enc_outputs, enc_outputs, padding_mask)
        attn2 = self.dropout2(attn2)
        out2 = self.layernorm2(out1 + attn2)

        ffn_output = self.ffn(out2)
        ffn_output = self.dropout3(ffn_output)
        out3 = self.layernorm3(out2 + ffn_output)

        return out3


class Decoder(nn.Module):
    def __init__(self, vocab_size, num_layers, ff_dim, d_model, num_heads, dropout=0.1):
        super(Decoder, self).__init__()

        self.d_model = d_model
        self.num_layers = num_layers

        self.embedding = nn.Embedding(vocab_size, d_model)
        self.pos_encoding = PositionalEncoding(1000, d_model)

        self.dec_layers = nn.ModuleList([
            DecoderLayer(d_model, num_heads, ff_dim, dropout)
            for _ in range(num_layers)
        ])

        self.dropout = nn.Dropout(dropout)

    def forward(self, x, enc_outputs, look_ahead_mask, padding_mask):
        x = self.embedding(x)
        x *= math.sqrt(self.d_model)
        x = self.pos_encoding(x)
        x = self.dropout(x)

        for i in range(self.num_layers):
            x = self.dec_layers[i](
                x,
                enc_outputs,
                look_ahead_mask,
                padding_mask
            )

        return x

In [41]:
class Transformer(nn.Module):
    def __init__(self,
                 vocab_size,
                 num_layers,
                 units,
                 d_model,
                 num_heads,
                 dropout=0.1):
        super(Transformer, self).__init__()

        self.encoder = Encoder(
            vocab_size=vocab_size,
            num_layers=num_layers,
            ff_dim=units,
            d_model=d_model,
            num_heads=num_heads,
            dropout=dropout
        )

        self.decoder = Decoder(
            vocab_size=vocab_size,
            num_layers=num_layers,
            ff_dim=units,
            d_model=d_model,
            num_heads=num_heads,
            dropout=dropout
        )

        self.final_linear = nn.Linear(d_model, vocab_size)

    def forward(self, inputs, dec_inputs):
        enc_padding_mask = create_padding_mask(inputs)
        look_ahead_mask = create_look_ahead_mask(dec_inputs)
        dec_padding_mask = create_padding_mask(inputs)

        enc_outputs = self.encoder(inputs, enc_padding_mask)

        dec_outputs = self.decoder(
            dec_inputs,
            enc_outputs,
            look_ahead_mask,
            dec_padding_mask
        )

        logits = self.final_linear(dec_outputs)

        return logits

In [42]:
needed_names = [
    "PositionalEncoding",
    "scaled_dot_product_attention",
    "MultiHeadAttention",
    "EncoderLayer",
    "Encoder",
    "DecoderLayer",
    "Decoder",
    "Transformer",
    "create_padding_mask",
    "create_look_ahead_mask"
]

for name in needed_names:
    print(name, "정의 여부:", name in globals())

PositionalEncoding 정의 여부: True
scaled_dot_product_attention 정의 여부: True
MultiHeadAttention 정의 여부: True
EncoderLayer 정의 여부: True
Encoder 정의 여부: True
DecoderLayer 정의 여부: True
Decoder 정의 여부: True
Transformer 정의 여부: True
create_padding_mask 정의 여부: True
create_look_ahead_mask 정의 여부: True

In [43]:
model = Transformer(
    vocab_size=VOCAB_SIZE,
    num_layers=NUM_LAYERS,
    units=UNITS,
    d_model=D_MODEL,
    num_heads=NUM_HEADS,
    dropout=DROPOUT
)

print("모델 생성 완료")
print(model)

모델 생성 완료
Transformer(
  (encoder): Encoder(
    (embedding): Embedding(8000, 256)
    (pos_encoding): PositionalEncoding()
    (enc_layers): ModuleList(
      (0-1): 2 x EncoderLayer(
        (mha): MultiHeadAttention(
          (query_dense): Linear(in_features=256, out_features=256, bias=True)
          (key_dense): Linear(in_features=256, out_features=256, bias=True)
          (value_dense): Linear(in_features=256, out_features=256, bias=True)
          (out_dense): Linear(in_features=256, out_features=256, bias=True)
        )
        (ffn): Sequential(
          (0): Linear(in_features=256, out_features=512, bias=True)
          (1): ReLU()
          (2): Linear(in_features=512, out_features=256, bias=True)
        )
        (layernorm1): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
        (layernorm2): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
        (dropout1): Dropout(p=0.1, inplace=False)
        (dropout2): Dropout(p=0.1, inplace=False)
      )
    )
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): Decoder(
    (embedding): Embedding(8000, 256)
    (pos_encoding): PositionalEncoding()
    (dec_layers): ModuleList(
      (0-1): 2 x DecoderLayer(
        (self_mha): MultiHeadAttention(
          (query_dense): Linear(in_features=256, out_features=256, bias=True)
          (key_dense): Linear(in_features=256, out_features=256, bias=True)
          (value_dense): Linear(in_features=256, out_features=256, bias=True)
          (out_dense): Linear(in_features=256, out_features=256, bias=True)
        )
        (enc_dec_mha): MultiHeadAttention(
          (query_dense): Linear(in_features=256, out_features=256, bias=True)
          (key_dense): Linear(in_features=256, out_features=256, bias=True)
          (value_dense): Linear(in_features=256, out_features=256, bias=True)
          (out_dense): Linear(in_features=256, out_features=256, bias=True)
        )
        (ffn): Sequential(
          (0): Linear(in_features=256, out_features=512, bias=True)
          (1): ReLU()
          (2): Linear(in_features=512, out_features=256, bias=True)
        )
        (layernorm1): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
        (layernorm2): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
        (layernorm3): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
        (dropout1): Dropout(p=0.1, inplace=False)
        (dropout2): Dropout(p=0.1, inplace=False)
        (dropout3): Dropout(p=0.1, inplace=False)
      )
    )
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (final_linear): Linear(in_features=256, out_features=8000, bias=True)
)

In [44]:
for encoder_input, decoder_input, decoder_label in dataloader:
    sample_logits = model(encoder_input, decoder_input)
    print("sample_logits 크기:", sample_logits.size())
    break

sample_logits 크기: torch.Size([32, 39, 8000])

In [45]:
loss_function = torch.nn.CrossEntropyLoss(ignore_index=sp.pad_id())

print("Loss 함수 생성 완료")
print("pad_id:", sp.pad_id())

Loss 함수 생성 완료
pad_id: 0

In [46]:
def get_lr_lambda(d_model, warmup_steps=4000):
    d_model = float(d_model)

    def lr_lambda(step):
        step = step + 1
        return (d_model ** -0.5) * min(
            step ** -0.5,
            step * (warmup_steps ** -1.5)
        )

    return lr_lambda

print("학습률 스케줄러 함수 정의 완료")

학습률 스케줄러 함수 정의 완료

In [47]:
import torch.optim as optim
import torch.optim.lr_scheduler as lr_scheduler

optimizer = optim.Adam(
    model.parameters(),
    lr=1.0,
    betas=(0.9, 0.98),
    eps=1e-9
)

scheduler = lr_scheduler.LambdaLR(
    optimizer,
    lr_lambda=get_lr_lambda(D_MODEL, warmup_steps=4000)
)

print("Optimizer / Scheduler 생성 완료")

Optimizer / Scheduler 생성 완료

In [48]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

print("device:", device)

device: cuda

In [49]:
def accuracy_function(y_pred, y_true, pad_id=0):
    """
    y_pred: (batch_size, seq_len, vocab_size)
    y_true: (batch_size, seq_len)
    """
    preds = y_pred.argmax(dim=-1)
    mask = (y_true != pad_id)

    correct = (preds == y_true) & mask
    acc = correct.float().sum() / mask.float().sum()

    return acc

In [50]:
def train_step(model, batch, optimizer, loss_function, device):
    model.train()

    enc_input, dec_input, target = [x.to(device) for x in batch]

    optimizer.zero_grad()

    logits = model(enc_input, dec_input)

    # CrossEntropyLoss는 class 차원(vocab_size)이 가운데 있어야 함
    loss = loss_function(logits.permute(0, 2, 1), target)

    loss.backward()

    # gradient 폭주 방지
    torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

    optimizer.step()

    acc = accuracy_function(logits, target, pad_id=sp.pad_id())

    return loss.item(), acc.item()

In [51]:
def train(model, dataloader, optimizer, loss_function, scheduler, num_epochs, device):
    model.to(device)

    for epoch in range(num_epochs):
        total_loss = 0
        total_acc = 0

        for step, batch in enumerate(dataloader):
            loss, acc = train_step(
                model,
                batch,
                optimizer,
                loss_function,
                device
            )

            total_loss += loss
            total_acc += acc

            scheduler.step()

            if step % 50 == 0:
                current_lr = scheduler.get_last_lr()[0]
                print(
                    f"[Epoch {epoch+1}, Step {step}] "
                    f"Loss: {loss:.4f}, Acc: {acc:.4f}, LR: {current_lr:.8f}"
                )

        avg_loss = total_loss / len(dataloader)
        avg_acc = total_acc / len(dataloader)

        print(
            f"Epoch {epoch+1} Completed - "
            f"Avg Loss: {avg_loss:.4f}, Avg Acc: {avg_acc:.4f}"
        )

In [52]:
%%time

train(
    model=model,
    dataloader=dataloader,
    optimizer=optimizer,
    loss_function=loss_function,
    scheduler=scheduler,
    num_epochs=1,
    device=device
)

[Epoch 1, Step 0] Loss: 9.0235, Acc: 0.0000, LR: 0.00000049
[Epoch 1, Step 50] Loss: 8.5414, Acc: 0.0474, LR: 0.00001285
[Epoch 1, Step 100] Loss: 7.5087, Acc: 0.2871, LR: 0.00002520
[Epoch 1, Step 150] Loss: 6.7729, Acc: 0.2968, LR: 0.00003755
[Epoch 1, Step 200] Loss: 6.6156, Acc: 0.2739, LR: 0.00004990
[Epoch 1, Step 250] Loss: 6.3215, Acc: 0.2616, LR: 0.00006226
[Epoch 1, Step 300] Loss: 6.0978, Acc: 0.3029, LR: 0.00007461
[Epoch 1, Step 350] Loss: 6.0690, Acc: 0.2851, LR: 0.00008696
Epoch 1 Completed - Avg Loss: 6.9881, Avg Acc: 0.2417
CPU times: user 16.5 s, sys: 307 ms, total: 16.8 s
Wall time: 11.4 s

In [53]:
%%time

train(
    model=model,
    dataloader=dataloader,
    optimizer=optimizer,
    loss_function=loss_function,
    scheduler=scheduler,
    num_epochs=4,
    device=device
)

[Epoch 1, Step 0] Loss: 5.9080, Acc: 0.2723, LR: 0.00009190
[Epoch 1, Step 50] Loss: 5.5780, Acc: 0.2977, LR: 0.00010426
[Epoch 1, Step 100] Loss: 5.8797, Acc: 0.2731, LR: 0.00011661
[Epoch 1, Step 150] Loss: 5.7185, Acc: 0.3053, LR: 0.00012896
[Epoch 1, Step 200] Loss: 5.8632, Acc: 0.2791, LR: 0.00014131
[Epoch 1, Step 250] Loss: 5.2896, Acc: 0.3259, LR: 0.00015367
[Epoch 1, Step 300] Loss: 5.5333, Acc: 0.3077, LR: 0.00016602
[Epoch 1, Step 350] Loss: 5.5963, Acc: 0.2960, LR: 0.00017837
Epoch 1 Completed - Avg Loss: 5.6563, Avg Acc: 0.3014
[Epoch 2, Step 0] Loss: 5.6190, Acc: 0.2708, LR: 0.00018331
[Epoch 2, Step 50] Loss: 5.5730, Acc: 0.2915, LR: 0.00019567
[Epoch 2, Step 100] Loss: 5.0734, Acc: 0.3364, LR: 0.00020802
[Epoch 2, Step 150] Loss: 5.5000, Acc: 0.3125, LR: 0.00022037
[Epoch 2, Step 200] Loss: 5.0302, Acc: 0.3226, LR: 0.00023272
[Epoch 2, Step 250] Loss: 4.8326, Acc: 0.3541, LR: 0.00024508
[Epoch 2, Step 300] Loss: 5.1311, Acc: 0.3300, LR: 0.00025743
[Epoch 2, Step 350] Loss: 5.2686, Acc: 0.2990, LR: 0.00026978
Epoch 2 Completed - Avg Loss: 5.1887, Avg Acc: 0.3200
[Epoch 3, Step 0] Loss: 5.0481, Acc: 0.2946, LR: 0.00027472
[Epoch 3, Step 50] Loss: 4.9055, Acc: 0.3303, LR: 0.00028708
[Epoch 3, Step 100] Loss: 4.7146, Acc: 0.3377, LR: 0.00029943
[Epoch 3, Step 150] Loss: 4.9142, Acc: 0.3151, LR: 0.00031178
[Epoch 3, Step 200] Loss: 4.5810, Acc: 0.3641, LR: 0.00032413
[Epoch 3, Step 250] Loss: 4.9650, Acc: 0.3169, LR: 0.00033649
[Epoch 3, Step 300] Loss: 4.2995, Acc: 0.4241, LR: 0.00034884
[Epoch 3, Step 350] Loss: 4.8265, Acc: 0.3511, LR: 0.00036119
Epoch 3 Completed - Avg Loss: 4.7082, Avg Acc: 0.3457
[Epoch 4, Step 0] Loss: 4.4478, Acc: 0.3348, LR: 0.00036613
[Epoch 4, Step 50] Loss: 4.3478, Acc: 0.3990, LR: 0.00037849
[Epoch 4, Step 100] Loss: 4.1907, Acc: 0.4010, LR: 0.00039084
[Epoch 4, Step 150] Loss: 4.2677, Acc: 0.3584, LR: 0.00040319
[Epoch 4, Step 200] Loss: 4.5477, Acc: 0.3436, LR: 0.00041554
[Epoch 4, Step 250] Loss: 4.0984, Acc: 0.3771, LR: 0.00042790
[Epoch 4, Step 300] Loss: 4.5772, Acc: 0.3239, LR: 0.00044025
[Epoch 4, Step 350] Loss: 4.1588, Acc: 0.3870, LR: 0.00045260
Epoch 4 Completed - Avg Loss: 4.2349, Avg Acc: 0.3781
CPU times: user 1min 5s, sys: 324 ms, total: 1min 5s
Wall time: 43.4 s

In [54]:
model_save_path = os.path.join(project_dir, "korean_transformer_chatbot.pt")

torch.save({
    "model_state_dict": model.state_dict(),
    "optimizer_state_dict": optimizer.state_dict(),
    "scheduler_state_dict": scheduler.state_dict(),
    "vocab_size": VOCAB_SIZE,
    "num_layers": NUM_LAYERS,
    "d_model": D_MODEL,
    "num_heads": NUM_HEADS,
    "units": UNITS,
    "dropout": DROPOUT,
}, model_save_path)

print("모델 저장 완료:", model_save_path)
print("파일 존재 여부:", os.path.exists(model_save_path))

모델 저장 완료: /home/jovyan/work/transformer_chatbot/korean_transformer_chatbot.pt
파일 존재 여부: True

In [145]:
def decoder_inference(model, sentence, tokenizer, device='cpu', max_length=40):
    START_TOKEN = tokenizer.bos_id()
    END_TOKEN = tokenizer.eos_id()
    PAD_TOKEN = tokenizer.pad_id()

    # 1. 입력 문장 전처리
    sentence = preprocess_sentence(sentence)

    # 2. 입력 문장 인코딩
    enc_input_ids = [START_TOKEN] + tokenizer.encode(sentence, out_type=int) + [END_TOKEN]
    enc_input_ids = enc_input_ids[:max_length]

    # 3. 인코더 입력 텐서 생성
    enc_input = torch.tensor([enc_input_ids], dtype=torch.long, device=device)

    # 4. 디코더 입력은 START_TOKEN에서 시작
    dec_input = torch.tensor([[START_TOKEN]], dtype=torch.long, device=device)

    model.eval()

    with torch.no_grad():
        for _ in range(max_length):
            logits = model(enc_input, dec_input)

            # 마지막 위치의 vocab 점수만 사용
            last_step_logits = logits[:, -1, :]

            # 가장 확률 높은 토큰 선택
            predicted_id = torch.argmax(last_step_logits, dim=-1)

            # END_TOKEN 나오면 종료
            if predicted_id.item() == END_TOKEN:
                break

            # 예측 토큰을 디코더 입력 뒤에 붙이기
            predicted_id = predicted_id.unsqueeze(0)
            dec_input = torch.cat([dec_input, predicted_id], dim=1)

            if dec_input.size(1) >= max_length:
                break

    output_sequence = dec_input.squeeze(0).tolist()

    # START, END, PAD 제거
    output_sequence = [
        token for token in output_sequence
        if token not in [START_TOKEN, END_TOKEN, PAD_TOKEN]
    ]

    return output_sequence

In [156]:
%%time

train(
    model=model,
    dataloader=dataloader,
    optimizer=optimizer,
    loss_function=loss_function,
    scheduler=scheduler,
    num_epochs=20,
    device=device
)

[Epoch 1, Step 0] Loss: 0.0095, Acc: 1.0000, LR: 0.00024920
[Epoch 1, Step 50] Loss: 0.0244, Acc: 0.9955, LR: 0.00024910
[Epoch 1, Step 100] Loss: 0.0220, Acc: 0.9956, LR: 0.00024900
[Epoch 1, Step 150] Loss: 0.0351, Acc: 0.9960, LR: 0.00024890
[Epoch 1, Step 200] Loss: 0.0637, Acc: 0.9871, LR: 0.00024880
[Epoch 1, Step 250] Loss: 0.0412, Acc: 0.9952, LR: 0.00024871
[Epoch 1, Step 300] Loss: 0.0442, Acc: 0.9951, LR: 0.00024861
[Epoch 1, Step 350] Loss: 0.0624, Acc: 0.9902, LR: 0.00024851
Epoch 1 Completed - Avg Loss: 0.0374, Avg Acc: 0.9954
[Epoch 2, Step 0] Loss: 0.0086, Acc: 1.0000, LR: 0.00024847
[Epoch 2, Step 50] Loss: 0.0155, Acc: 1.0000, LR: 0.00024837
[Epoch 2, Step 100] Loss: 0.0174, Acc: 1.0000, LR: 0.00024827
[Epoch 2, Step 150] Loss: 0.0594, Acc: 0.9906, LR: 0.00024818
[Epoch 2, Step 200] Loss: 0.0362, Acc: 0.9954, LR: 0.00024808
[Epoch 2, Step 250] Loss: 0.0451, Acc: 0.9952, LR: 0.00024798
[Epoch 2, Step 300] Loss: 0.0180, Acc: 1.0000, LR: 0.00024788
[Epoch 2, Step 350] Loss: 0.0756, Acc: 0.9951, LR: 0.00024779
Epoch 2 Completed - Avg Loss: 0.0384, Avg Acc: 0.9952
[Epoch 3, Step 0] Loss: 0.0098, Acc: 1.0000, LR: 0.00024775
[Epoch 3, Step 50] Loss: 0.0352, Acc: 0.9949, LR: 0.00024765
[Epoch 3, Step 100] Loss: 0.0638, Acc: 0.9857, LR: 0.00024755
[Epoch 3, Step 150] Loss: 0.0675, Acc: 0.9910, LR: 0.00024746
[Epoch 3, Step 200] Loss: 0.0100, Acc: 1.0000, LR: 0.00024736
[Epoch 3, Step 250] Loss: 0.0189, Acc: 1.0000, LR: 0.00024726
[Epoch 3, Step 300] Loss: 0.0269, Acc: 0.9949, LR: 0.00024716
[Epoch 3, Step 350] Loss: 0.0800, Acc: 0.9903, LR: 0.00024707
Epoch 3 Completed - Avg Loss: 0.0384, Avg Acc: 0.9953
[Epoch 4, Step 0] Loss: 0.0220, Acc: 0.9956, LR: 0.00024703
[Epoch 4, Step 50] Loss: 0.0311, Acc: 0.9955, LR: 0.00024693
[Epoch 4, Step 100] Loss: 0.0096, Acc: 1.0000, LR: 0.00024684
[Epoch 4, Step 150] Loss: 0.0152, Acc: 1.0000, LR: 0.00024674
[Epoch 4, Step 200] Loss: 0.0122, Acc: 1.0000, LR: 0.00024664
[Epoch 4, Step 250] Loss: 0.0831, Acc: 0.9911, LR: 0.00024655
[Epoch 4, Step 300] Loss: 0.0878, Acc: 0.9844, LR: 0.00024645
[Epoch 4, Step 350] Loss: 0.0690, Acc: 0.9874, LR: 0.00024636
Epoch 4 Completed - Avg Loss: 0.0374, Avg Acc: 0.9957
[Epoch 5, Step 0] Loss: 0.0191, Acc: 0.9955, LR: 0.00024632
[Epoch 5, Step 50] Loss: 0.0622, Acc: 0.9860, LR: 0.00024622
[Epoch 5, Step 100] Loss: 0.0275, Acc: 0.9950, LR: 0.00024613
[Epoch 5, Step 150] Loss: 0.0139, Acc: 1.0000, LR: 0.00024603
[Epoch 5, Step 200] Loss: 0.0140, Acc: 0.9952, LR: 0.00024594
[Epoch 5, Step 250] Loss: 0.0213, Acc: 1.0000, LR: 0.00024584
[Epoch 5, Step 300] Loss: 0.0773, Acc: 0.9920, LR: 0.00024575
[Epoch 5, Step 350] Loss: 0.0318, Acc: 1.0000, LR: 0.00024565
Epoch 5 Completed - Avg Loss: 0.0394, Avg Acc: 0.9951
[Epoch 6, Step 0] Loss: 0.0082, Acc: 1.0000, LR: 0.00024561
[Epoch 6, Step 50] Loss: 0.0082, Acc: 1.0000, LR: 0.00024552
[Epoch 6, Step 100] Loss: 0.0084, Acc: 1.0000, LR: 0.00024542
[Epoch 6, Step 150] Loss: 0.0190, Acc: 1.0000, LR: 0.00024533
[Epoch 6, Step 200] Loss: 0.0066, Acc: 1.0000, LR: 0.00024524
[Epoch 6, Step 250] Loss: 0.0163, Acc: 0.9954, LR: 0.00024514
[Epoch 6, Step 300] Loss: 0.0552, Acc: 0.9915, LR: 0.00024505
[Epoch 6, Step 350] Loss: 0.0246, Acc: 1.0000, LR: 0.00024495
Epoch 6 Completed - Avg Loss: 0.0353, Avg Acc: 0.9957
[Epoch 7, Step 0] Loss: 0.0480, Acc: 0.9956, LR: 0.00024492
[Epoch 7, Step 50] Loss: 0.0364, Acc: 0.9953, LR: 0.00024482
[Epoch 7, Step 100] Loss: 0.0096, Acc: 1.0000, LR: 0.00024473
[Epoch 7, Step 150] Loss: 0.1078, Acc: 0.9798, LR: 0.00024463
[Epoch 7, Step 200] Loss: 0.0575, Acc: 0.9961, LR: 0.00024454
[Epoch 7, Step 250] Loss: 0.0307, Acc: 1.0000, LR: 0.00024445
[Epoch 7, Step 300] Loss: 0.0244, Acc: 1.0000, LR: 0.00024435
[Epoch 7, Step 350] Loss: 0.0200, Acc: 1.0000, LR: 0.00024426
Epoch 7 Completed - Avg Loss: 0.0357, Avg Acc: 0.9958
[Epoch 8, Step 0] Loss: 0.0087, Acc: 1.0000, LR: 0.00024422
[Epoch 8, Step 50] Loss: 0.0107, Acc: 1.0000, LR: 0.00024413
[Epoch 8, Step 100] Loss: 0.0235, Acc: 0.9949, LR: 0.00024404
[Epoch 8, Step 150] Loss: 0.0410, Acc: 0.9956, LR: 0.00024394
[Epoch 8, Step 200] Loss: 0.0183, Acc: 1.0000, LR: 0.00024385
[Epoch 8, Step 250] Loss: 0.0274, Acc: 1.0000, LR: 0.00024376
[Epoch 8, Step 300] Loss: 0.0436, Acc: 0.9958, LR: 0.00024367
[Epoch 8, Step 350] Loss: 0.0832, Acc: 0.9907, LR: 0.00024357
Epoch 8 Completed - Avg Loss: 0.0374, Avg Acc: 0.9955
[Epoch 9, Step 0] Loss: 0.0330, Acc: 0.9955, LR: 0.00024354
[Epoch 9, Step 50] Loss: 0.0229, Acc: 0.9951, LR: 0.00024344
[Epoch 9, Step 100] Loss: 0.0115, Acc: 0.9952, LR: 0.00024335
[Epoch 9, Step 150] Loss: 0.0283, Acc: 1.0000, LR: 0.00024326
[Epoch 9, Step 200] Loss: 0.0340, Acc: 0.9916, LR: 0.00024317
[Epoch 9, Step 250] Loss: 0.0639, Acc: 0.9900, LR: 0.00024307
[Epoch 9, Step 300] Loss: 0.0536, Acc: 0.9949, LR: 0.00024298
[Epoch 9, Step 350] Loss: 0.0421, Acc: 0.9949, LR: 0.00024289
Epoch 9 Completed - Avg Loss: 0.0371, Avg Acc: 0.9956
[Epoch 10, Step 0] Loss: 0.0136, Acc: 0.9959, LR: 0.00024285
[Epoch 10, Step 50] Loss: 0.0460, Acc: 0.9919, LR: 0.00024276
[Epoch 10, Step 100] Loss: 0.0219, Acc: 0.9955, LR: 0.00024267
[Epoch 10, Step 150] Loss: 0.0184, Acc: 0.9953, LR: 0.00024258
[Epoch 10, Step 200] Loss: 0.0850, Acc: 0.9805, LR: 0.00024249
[Epoch 10, Step 250] Loss: 0.0327, Acc: 0.9912, LR: 0.00024240
[Epoch 10, Step 300] Loss: 0.0257, Acc: 0.9952, LR: 0.00024231
[Epoch 10, Step 350] Loss: 0.0117, Acc: 1.0000, LR: 0.00024222
Epoch 10 Completed - Avg Loss: 0.0367, Avg Acc: 0.9954
[Epoch 11, Step 0] Loss: 0.0111, Acc: 1.0000, LR: 0.00024218
[Epoch 11, Step 50] Loss: 0.0126, Acc: 1.0000, LR: 0.00024209
[Epoch 11, Step 100] Loss: 0.0211, Acc: 1.0000, LR: 0.00024200
[Epoch 11, Step 150] Loss: 0.0104, Acc: 1.0000, LR: 0.00024191
[Epoch 11, Step 200] Loss: 0.0190, Acc: 1.0000, LR: 0.00024182
[Epoch 11, Step 250] Loss: 0.1099, Acc: 0.9805, LR: 0.00024173
[Epoch 11, Step 300] Loss: 0.0749, Acc: 0.9920, LR: 0.00024164
[Epoch 11, Step 350] Loss: 0.0207, Acc: 1.0000, LR: 0.00024155
Epoch 11 Completed - Avg Loss: 0.0367, Avg Acc: 0.9955
[Epoch 12, Step 0] Loss: 0.0075, Acc: 1.0000, LR: 0.00024151
[Epoch 12, Step 50] Loss: 0.0472, Acc: 0.9905, LR: 0.00024142
[Epoch 12, Step 100] Loss: 0.0120, Acc: 1.0000, LR: 0.00024133
[Epoch 12, Step 150] Loss: 0.0155, Acc: 1.0000, LR: 0.00024124
[Epoch 12, Step 200] Loss: 0.0131, Acc: 1.0000, LR: 0.00024115
[Epoch 12, Step 250] Loss: 0.0913, Acc: 0.9901, LR: 0.00024106
[Epoch 12, Step 300] Loss: 0.0673, Acc: 0.9867, LR: 0.00024097
[Epoch 12, Step 350] Loss: 0.1519, Acc: 0.9790, LR: 0.00024088
Epoch 12 Completed - Avg Loss: 0.0361, Avg Acc: 0.9952
[Epoch 13, Step 0] Loss: 0.0052, Acc: 1.0000, LR: 0.00024084
[Epoch 13, Step 50] Loss: 0.0202, Acc: 1.0000, LR: 0.00024076
[Epoch 13, Step 100] Loss: 0.0165, Acc: 0.9951, LR: 0.00024067
[Epoch 13, Step 150] Loss: 0.0331, Acc: 0.9945, LR: 0.00024058
[Epoch 13, Step 200] Loss: 0.0434, Acc: 0.9956, LR: 0.00024049
[Epoch 13, Step 250] Loss: 0.0735, Acc: 0.9922, LR: 0.00024040
[Epoch 13, Step 300] Loss: 0.0131, Acc: 1.0000, LR: 0.00024031
[Epoch 13, Step 350] Loss: 0.1037, Acc: 0.9853, LR: 0.00024022
Epoch 13 Completed - Avg Loss: 0.0354, Avg Acc: 0.9956
[Epoch 14, Step 0] Loss: 0.0169, Acc: 0.9954, LR: 0.00024019
[Epoch 14, Step 50] Loss: 0.0063, Acc: 1.0000, LR: 0.00024010
[Epoch 14, Step 100] Loss: 0.0086, Acc: 1.0000, LR: 0.00024001
[Epoch 14, Step 150] Loss: 0.0864, Acc: 0.9898, LR: 0.00023992
[Epoch 14, Step 200] Loss: 0.0271, Acc: 0.9953, LR: 0.00023983
[Epoch 14, Step 250] Loss: 0.0281, Acc: 1.0000, LR: 0.00023974
[Epoch 14, Step 300] Loss: 0.0716, Acc: 0.9869, LR: 0.00023966
[Epoch 14, Step 350] Loss: 0.0726, Acc: 0.9905, LR: 0.00023957
Epoch 14 Completed - Avg Loss: 0.0371, Avg Acc: 0.9953
[Epoch 15, Step 0] Loss: 0.0124, Acc: 1.0000, LR: 0.00023953
[Epoch 15, Step 50] Loss: 0.0081, Acc: 1.0000, LR: 0.00023944
[Epoch 15, Step 100] Loss: 0.0052, Acc: 1.0000, LR: 0.00023936
[Epoch 15, Step 150] Loss: 0.0368, Acc: 0.9950, LR: 0.00023927
[Epoch 15, Step 200] Loss: 0.0116, Acc: 1.0000, LR: 0.00023918
[Epoch 15, Step 250] Loss: 0.0347, Acc: 0.9960, LR: 0.00023909
[Epoch 15, Step 300] Loss: 0.0485, Acc: 0.9918, LR: 0.00023901
[Epoch 15, Step 350] Loss: 0.0624, Acc: 0.9906, LR: 0.00023892
Epoch 15 Completed - Avg Loss: 0.0367, Avg Acc: 0.9953
[Epoch 16, Step 0] Loss: 0.0071, Acc: 1.0000, LR: 0.00023888
[Epoch 16, Step 50] Loss: 0.0218, Acc: 0.9954, LR: 0.00023880
[Epoch 16, Step 100] Loss: 0.0425, Acc: 0.9912, LR: 0.00023871
[Epoch 16, Step 150] Loss: 0.0082, Acc: 1.0000, LR: 0.00023862
[Epoch 16, Step 200] Loss: 0.0394, Acc: 0.9956, LR: 0.00023854
[Epoch 16, Step 250] Loss: 0.0856, Acc: 0.9860, LR: 0.00023845
[Epoch 16, Step 300] Loss: 0.0651, Acc: 0.9948, LR: 0.00023836
[Epoch 16, Step 350] Loss: 0.1282, Acc: 0.9764, LR: 0.00023828
Epoch 16 Completed - Avg Loss: 0.0377, Avg Acc: 0.9954
[Epoch 17, Step 0] Loss: 0.0071, Acc: 1.0000, LR: 0.00023824
[Epoch 17, Step 50] Loss: 0.0109, Acc: 1.0000, LR: 0.00023815
[Epoch 17, Step 100] Loss: 0.0239, Acc: 0.9958, LR: 0.00023807
[Epoch 17, Step 150] Loss: 0.0490, Acc: 0.9913, LR: 0.00023798
[Epoch 17, Step 200] Loss: 0.0372, Acc: 0.9872, LR: 0.00023790
[Epoch 17, Step 250] Loss: 0.0368, Acc: 0.9905, LR: 0.00023781
[Epoch 17, Step 300] Loss: 0.1238, Acc: 0.9874, LR: 0.00023772
[Epoch 17, Step 350] Loss: 0.1158, Acc: 0.9825, LR: 0.00023764
Epoch 17 Completed - Avg Loss: 0.0367, Avg Acc: 0.9954
[Epoch 18, Step 0] Loss: 0.0040, Acc: 1.0000, LR: 0.00023760
[Epoch 18, Step 50] Loss: 0.0284, Acc: 0.9956, LR: 0.00023752
[Epoch 18, Step 100] Loss: 0.0128, Acc: 1.0000, LR: 0.00023743
[Epoch 18, Step 150] Loss: 0.0138, Acc: 1.0000, LR: 0.00023735
[Epoch 18, Step 200] Loss: 0.0244, Acc: 1.0000, LR: 0.00023726
[Epoch 18, Step 250] Loss: 0.0380, Acc: 0.9959, LR: 0.00023717
[Epoch 18, Step 300] Loss: 0.0295, Acc: 1.0000, LR: 0.00023709
[Epoch 18, Step 350] Loss: 0.0682, Acc: 0.9907, LR: 0.00023700
Epoch 18 Completed - Avg Loss: 0.0369, Avg Acc: 0.9954
[Epoch 19, Step 0] Loss: 0.0069, Acc: 1.0000, LR: 0.00023697
[Epoch 19, Step 50] Loss: 0.0124, Acc: 1.0000, LR: 0.00023689
[Epoch 19, Step 100] Loss: 0.0520, Acc: 0.9953, LR: 0.00023680
[Epoch 19, Step 150] Loss: 0.1569, Acc: 0.9756, LR: 0.00023672
[Epoch 19, Step 200] Loss: 0.0615, Acc: 0.9911, LR: 0.00023663
[Epoch 19, Step 250] Loss: 0.0873, Acc: 0.9862, LR: 0.00023655
[Epoch 19, Step 300] Loss: 0.1123, Acc: 0.9851, LR: 0.00023646
[Epoch 19, Step 350] Loss: 0.0624, Acc: 0.9868, LR: 0.00023638
Epoch 19 Completed - Avg Loss: 0.0395, Avg Acc: 0.9951
[Epoch 20, Step 0] Loss: 0.2088, Acc: 0.9724, LR: 0.00023634
[Epoch 20, Step 50] Loss: 0.0199, Acc: 0.9951, LR: 0.00023626
[Epoch 20, Step 100] Loss: 0.0357, Acc: 0.9902, LR: 0.00023617
[Epoch 20, Step 150] Loss: 0.0597, Acc: 0.9914, LR: 0.00023609
[Epoch 20, Step 200] Loss: 0.0479, Acc: 1.0000, LR: 0.00023601
[Epoch 20, Step 250] Loss: 0.0350, Acc: 0.9956, LR: 0.00023592
[Epoch 20, Step 300] Loss: 0.0258, Acc: 1.0000, LR: 0.00023584
[Epoch 20, Step 350] Loss: 0.0408, Acc: 0.9950, LR: 0.00023575
Epoch 20 Completed - Avg Loss: 0.0381, Avg Acc: 0.9954
CPU times: user 5min 25s, sys: 1.71 s, total: 5min 27s
Wall time: 3min 35s

In [144]:
torch.save({
    "model_state_dict": model.state_dict(),
    "optimizer_state_dict": optimizer.state_dict(),
    "scheduler_state_dict": scheduler.state_dict(),
    "vocab_size": VOCAB_SIZE,
    "num_layers": NUM_LAYERS,
    "d_model": D_MODEL,
    "num_heads": NUM_HEADS,
    "units": UNITS,
    "dropout": DROPOUT,
}, model_save_path)

print("20 epoch 추가 학습 후 모델 저장 완료:", model_save_path)
print("파일 존재 여부:", os.path.exists(model_save_path))

20 epoch 추가 학습 후 모델 저장 완료: /home/jovyan/work/transformer_chatbot/korean_transformer_chatbot.pt
파일 존재 여부: True

In [146]:
%%time

train(
    model=model,
    dataloader=dataloader,
    optimizer=optimizer,
    loss_function=loss_function,
    scheduler=scheduler,
    num_epochs=10,
    device=device
)

[Epoch 1, Step 0] Loss: 0.0101, Acc: 1.0000, LR: 0.00025687
[Epoch 1, Step 50] Loss: 0.0103, Acc: 1.0000, LR: 0.00025676
[Epoch 1, Step 100] Loss: 0.0225, Acc: 1.0000, LR: 0.00025665
[Epoch 1, Step 150] Loss: 0.0198, Acc: 1.0000, LR: 0.00025654
[Epoch 1, Step 200] Loss: 0.0457, Acc: 0.9904, LR: 0.00025644
[Epoch 1, Step 250] Loss: 0.0308, Acc: 0.9959, LR: 0.00025633
[Epoch 1, Step 300] Loss: 0.0723, Acc: 0.9862, LR: 0.00025622
[Epoch 1, Step 350] Loss: 0.0261, Acc: 1.0000, LR: 0.00025611
Epoch 1 Completed - Avg Loss: 0.0381, Avg Acc: 0.9953
[Epoch 2, Step 0] Loss: 0.0119, Acc: 1.0000, LR: 0.00025607
[Epoch 2, Step 50] Loss: 0.0115, Acc: 1.0000, LR: 0.00025596
[Epoch 2, Step 100] Loss: 0.0143, Acc: 1.0000, LR: 0.00025586
[Epoch 2, Step 150] Loss: 0.0834, Acc: 0.9865, LR: 0.00025575
[Epoch 2, Step 200] Loss: 0.0068, Acc: 1.0000, LR: 0.00025564
[Epoch 2, Step 250] Loss: 0.0629, Acc: 0.9903, LR: 0.00025553
[Epoch 2, Step 300] Loss: 0.0451, Acc: 0.9947, LR: 0.00025543
[Epoch 2, Step 350] Loss: 0.0750, Acc: 0.9855, LR: 0.00025532
Epoch 2 Completed - Avg Loss: 0.0373, Avg Acc: 0.9955
[Epoch 3, Step 0] Loss: 0.0081, Acc: 1.0000, LR: 0.00025528
[Epoch 3, Step 50] Loss: 0.0390, Acc: 0.9851, LR: 0.00025517
[Epoch 3, Step 100] Loss: 0.0365, Acc: 0.9955, LR: 0.00025507
[Epoch 3, Step 150] Loss: 0.0089, Acc: 1.0000, LR: 0.00025496
[Epoch 3, Step 200] Loss: 0.0159, Acc: 1.0000, LR: 0.00025485
[Epoch 3, Step 250] Loss: 0.0209, Acc: 0.9956, LR: 0.00025475
[Epoch 3, Step 300] Loss: 0.0432, Acc: 0.9956, LR: 0.00025464
[Epoch 3, Step 350] Loss: 0.0756, Acc: 0.9909, LR: 0.00025454
Epoch 3 Completed - Avg Loss: 0.0376, Avg Acc: 0.9953
[Epoch 4, Step 0] Loss: 0.0271, Acc: 0.9955, LR: 0.00025449
[Epoch 4, Step 50] Loss: 0.0284, Acc: 1.0000, LR: 0.00025439
[Epoch 4, Step 100] Loss: 0.0474, Acc: 0.9832, LR: 0.00025428
[Epoch 4, Step 150] Loss: 0.0068, Acc: 1.0000, LR: 0.00025418
[Epoch 4, Step 200] Loss: 0.0357, Acc: 0.9950, LR: 0.00025407
[Epoch 4, Step 250] Loss: 0.0667, Acc: 0.9897, LR: 0.00025397
[Epoch 4, Step 300] Loss: 0.0146, Acc: 1.0000, LR: 0.00025386
[Epoch 4, Step 350] Loss: 0.0407, Acc: 0.9949, LR: 0.00025376
Epoch 4 Completed - Avg Loss: 0.0378, Avg Acc: 0.9952
[Epoch 5, Step 0] Loss: 0.0115, Acc: 1.0000, LR: 0.00025372
[Epoch 5, Step 50] Loss: 0.0070, Acc: 1.0000, LR: 0.00025361
[Epoch 5, Step 100] Loss: 0.0125, Acc: 1.0000, LR: 0.00025351
[Epoch 5, Step 150] Loss: 0.0461, Acc: 0.9953, LR: 0.00025340
[Epoch 5, Step 200] Loss: 0.0996, Acc: 0.9862, LR: 0.00025330
[Epoch 5, Step 250] Loss: 0.0141, Acc: 1.0000, LR: 0.00025320
[Epoch 5, Step 300] Loss: 0.0586, Acc: 0.9907, LR: 0.00025309
[Epoch 5, Step 350] Loss: 0.0458, Acc: 0.9909, LR: 0.00025299
Epoch 5 Completed - Avg Loss: 0.0382, Avg Acc: 0.9953
[Epoch 6, Step 0] Loss: 0.0067, Acc: 1.0000, LR: 0.00025295
[Epoch 6, Step 50] Loss: 0.0087, Acc: 1.0000, LR: 0.00025284
[Epoch 6, Step 100] Loss: 0.0174, Acc: 0.9954, LR: 0.00025274
[Epoch 6, Step 150] Loss: 0.0120, Acc: 1.0000, LR: 0.00025264
[Epoch 6, Step 200] Loss: 0.0316, Acc: 1.0000, LR: 0.00025253
[Epoch 6, Step 250] Loss: 0.0362, Acc: 0.9956, LR: 0.00025243
[Epoch 6, Step 300] Loss: 0.0523, Acc: 0.9917, LR: 0.00025233
[Epoch 6, Step 350] Loss: 0.1434, Acc: 0.9732, LR: 0.00025223
Epoch 6 Completed - Avg Loss: 0.0390, Avg Acc: 0.9951
[Epoch 7, Step 0] Loss: 0.0252, Acc: 0.9955, LR: 0.00025218
[Epoch 7, Step 50] Loss: 0.0243, Acc: 1.0000, LR: 0.00025208
[Epoch 7, Step 100] Loss: 0.0494, Acc: 0.9862, LR: 0.00025198
[Epoch 7, Step 150] Loss: 0.0510, Acc: 0.9953, LR: 0.00025188
[Epoch 7, Step 200] Loss: 0.0132, Acc: 1.0000, LR: 0.00025177
[Epoch 7, Step 250] Loss: 0.0242, Acc: 0.9953, LR: 0.00025167
[Epoch 7, Step 300] Loss: 0.0857, Acc: 0.9910, LR: 0.00025157
[Epoch 7, Step 350] Loss: 0.0539, Acc: 0.9950, LR: 0.00025147
Epoch 7 Completed - Avg Loss: 0.0410, Avg Acc: 0.9949
[Epoch 8, Step 0] Loss: 0.0164, Acc: 0.9956, LR: 0.00025143
[Epoch 8, Step 50] Loss: 0.0294, Acc: 0.9955, LR: 0.00025133
[Epoch 8, Step 100] Loss: 0.0164, Acc: 1.0000, LR: 0.00025122
[Epoch 8, Step 150] Loss: 0.0359, Acc: 0.9900, LR: 0.00025112
[Epoch 8, Step 200] Loss: 0.0994, Acc: 0.9865, LR: 0.00025102
[Epoch 8, Step 250] Loss: 0.0846, Acc: 0.9896, LR: 0.00025092
[Epoch 8, Step 300] Loss: 0.0339, Acc: 0.9953, LR: 0.00025082
[Epoch 8, Step 350] Loss: 0.0234, Acc: 1.0000, LR: 0.00025072
Epoch 8 Completed - Avg Loss: 0.0398, Avg Acc: 0.9952
[Epoch 9, Step 0] Loss: 0.0271, Acc: 0.9952, LR: 0.00025068
[Epoch 9, Step 50] Loss: 0.0117, Acc: 1.0000, LR: 0.00025058
[Epoch 9, Step 100] Loss: 0.0269, Acc: 0.9952, LR: 0.00025048
[Epoch 9, Step 150] Loss: 0.0492, Acc: 0.9949, LR: 0.00025038
[Epoch 9, Step 200] Loss: 0.0091, Acc: 1.0000, LR: 0.00025028
[Epoch 9, Step 250] Loss: 0.0792, Acc: 0.9909, LR: 0.00025018
[Epoch 9, Step 300] Loss: 0.0327, Acc: 0.9955, LR: 0.00025008
[Epoch 9, Step 350] Loss: 0.1989, Acc: 0.9725, LR: 0.00024998
Epoch 9 Completed - Avg Loss: 0.0366, Avg Acc: 0.9955
[Epoch 10, Step 0] Loss: 0.0062, Acc: 1.0000, LR: 0.00024994
[Epoch 10, Step 50] Loss: 0.0178, Acc: 0.9951, LR: 0.00024984
[Epoch 10, Step 100] Loss: 0.0327, Acc: 0.9958, LR: 0.00024974
[Epoch 10, Step 150] Loss: 0.0438, Acc: 0.9896, LR: 0.00024964
[Epoch 10, Step 200] Loss: 0.0348, Acc: 0.9949, LR: 0.00024954
[Epoch 10, Step 250] Loss: 0.0179, Acc: 1.0000, LR: 0.00024944
[Epoch 10, Step 300] Loss: 0.0579, Acc: 0.9953, LR: 0.00024934
[Epoch 10, Step 350] Loss: 0.0347, Acc: 0.9951, LR: 0.00024924
Epoch 10 Completed - Avg Loss: 0.0386, Avg Acc: 0.9952
CPU times: user 2min 50s, sys: 939 ms, total: 2min 51s
Wall time: 1min 53s

In [143]:
torch.save({
    "model_state_dict": model.state_dict(),
    "optimizer_state_dict": optimizer.state_dict(),
    "scheduler_state_dict": scheduler.state_dict(),
    "vocab_size": VOCAB_SIZE,
    "num_layers": NUM_LAYERS,
    "d_model": D_MODEL,
    "num_heads": NUM_HEADS,
    "units": UNITS,
    "dropout": DROPOUT,
}, model_save_path)

print("10 epoch 추가 학습 후 모델 저장 완료:", model_save_path)
print("파일 존재 여부:", os.path.exists(model_save_path))

10 epoch 추가 학습 후 모델 저장 완료: /home/jovyan/work/transformer_chatbot/korean_transformer_chatbot.pt
파일 존재 여부: True

In [142]:
test_sentences = [
    "오늘 너무 보고싶은 사람이 있는데 어쩌면 좋을까?",
    "나 정말 깊은 사랑을 혼자했던 것 같아",
    "그 사람은 말수는 적지만 내게 집중하려고 노력하는 사람이었어.",
    "혹시 그 사람은 지금 내 생각하고 있을까?",
    "그 사람이 삶을 대하는 태도를 나도 닮고 싶었는데 내가 놓친 걸까?",
    "그 사람과의 관계를 다시 회복할 수 있을까?",
    "하루하루 스스로 신뢰를 적립하는 마음으로 최선을 다하고 있어."
]

test_results = []

for sentence in test_sentences:
    output = sentence_generation(model, sentence, sp, device)
    test_results.append((sentence, output))

result_df = pd.DataFrame(test_results, columns=["Input", "Generated Response"])
result_df

입력: 오늘 너무 보고싶은 사람이 있는데 어쩌면 좋을까?
출력: 천천히 다가가보세요 .
--------------------------------------------------------------------------------
입력: 나 정말 깊은 사랑을 혼자했던 것 같아
출력: 제가 당신을 좋아하고 있어요 .
--------------------------------------------------------------------------------
입력: 그 사람은 말수는 적지만 내게 집중하려고 노력하는 사람이었어.
출력: 맘 고생 많았어요 .
--------------------------------------------------------------------------------
입력: 혹시 그 사람은 지금 내 생각하고 있을까?
출력: 조금 후련해질 거예요 .
--------------------------------------------------------------------------------
입력: 그 사람이 삶을 대하는 태도를 나도 닮고 싶었는데 내가 놓친 걸까?
출력: 생각을 정리해 보는 건 어떨까요 .
--------------------------------------------------------------------------------
입력: 그 사람과의 관계를 다시 회복할 수 있을까?
출력: 새로운 데이트 코스를 찾아보세요 .
--------------------------------------------------------------------------------
입력: 하루하루 스스로 신뢰를 적립하는 마음으로 최선을 다하고 있어.
출력: 그런 생각을 들게 하는 사람 상종하지 마세요 .
--------------------------------------------------------------------------------

                                   Input          Generated Response
0            오늘 너무 보고싶은 사람이 있는데 어쩌면 좋을까?                천천히 다가가보세요 .
1                  나 정말 깊은 사랑을 혼자했던 것 같아           제가 당신을 좋아하고 있어요 .
2     그 사람은 말수는 적지만 내게 집중하려고 노력하는 사람이었어.                 맘 고생 많았어요 .
3                혹시 그 사람은 지금 내 생각하고 있을까?               조금 후련해질 거예요 .
4  그 사람이 삶을 대하는 태도를 나도 닮고 싶었는데 내가 놓친 걸까?         생각을 정리해 보는 건 어떨까요 .
5               그 사람과의 관계를 다시 회복할 수 있을까?         새로운 데이트 코스를 찾아보세요 .
6     하루하루 스스로 신뢰를 적립하는 마음으로 최선을 다하고 있어.  그런 생각을 들게 하는 사람 상종하지 마세요 .

In [155]:
test_sentences = [
    "오늘 날씨가 너무 흐리고 안좋네. 넌 어때?",
    "FOMO로 인해서 코딩 공부를 하는데 잘 안되네.",
    "너는 인문학 전공자이자 코딩 입문자가 이런 실습 수업 수강하는 거 어떻게 생각해?",
    "공부하는데 도움되는 행동이 좋을까? 불필요한 행동을 제거하는 게 좋을까?",
    "너는 나의 학습법에 대해서 어떻게 생각해?",
    "매일 적립하는 마음으로 학습하지만 제한된 시간 내에 집중하려니 어렵네."
]

test_results = []

for sentence in test_sentences:
    output = sentence_generation(model, sentence, sp, device)
    test_results.append((sentence, output))

result_df = pd.DataFrame(test_results, columns=["Input", "Generated Response"])
result_df

입력: 오늘 날씨가 너무 흐리고 안좋네. 넌 어때?
출력: 이제 일어날 시간이에요 .
--------------------------------------------------------------------------------
입력: FOMO로 인해서 코딩 공부를 하는데 잘 안되네.
출력: 잘 생각하셨어요 .
--------------------------------------------------------------------------------
입력: 너는 인문학 전공자이자 코딩 입문자가 이런 실습 수업 수강하는 거 어떻게 생각해?
출력: 맛있게 드세요 .
--------------------------------------------------------------------------------
입력: 공부하는데 도움되는 행동이 좋을까? 불필요한 행동을 제거하는 게 좋을까?
출력: 충분히 그럴 수 있어요 .
--------------------------------------------------------------------------------
입력: 너는 나의 학습법에 대해서 어떻게 생각해?
출력: 사탕 만들어요 .
--------------------------------------------------------------------------------
입력: 매일 적립하는 마음으로 학습하지만 제한된 시간 내에 집중하려니 어렵네.
출력: 할 순 있어요 .
--------------------------------------------------------------------------------

                                           Input Generated Response
0                       오늘 날씨가 너무 흐리고 안좋네. 넌 어때?     이제 일어날 시간이에요 .
1                    FOMO로 인해서 코딩 공부를 하는데 잘 안되네.         잘 생각하셨어요 .
2  너는 인문학 전공자이자 코딩 입문자가 이런 실습 수업 수강하는 거 어떻게 생각해?          맛있게 드세요 .
3       공부하는데 도움되는 행동이 좋을까? 불필요한 행동을 제거하는 게 좋을까?     충분히 그럴 수 있어요 .
4                        너는 나의 학습법에 대해서 어떻게 생각해?          사탕 만들어요 .
5        매일 적립하는 마음으로 학습하지만 제한된 시간 내에 집중하려니 어렵네.          할 순 있어요 .